<a href="https://colab.research.google.com/github/hillarymaximino/metodos_numericos/blob/main/Atividade_07_M%C3%A9todos_Num%C3%A9ricos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercício 5-1**

In [14]:
import numpy as np

MATRIZ = np.arange(12).reshape(3,4)
SLICE = MATRIZ[1, 3]
print(f"O elemento da matriz no índice (2,4) é: {SLICE}")

O elemento da matriz no índice (2,4) é: 7


**Exercise 5-2**

In [21]:
MATRIZ = np.arange(100).reshape(10,10)
SLICE = MATRIZ[0:5, 0:5]
print(f"A submatriz C1 é: \n {SLICE}")

A submatriz C1 é: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


**Exercise 5-3**

In [32]:
MATRIZ = np.arange(100).reshape(10,10)
A = MATRIZ[0:5, 0:5]
B = MATRIZ[5:10, 5:10]
C = MATRIZ[0:5, 5:10]
D = MATRIZ[5:10, 0:5]

TOPO = np.hstack((B, D))
BAIXO = np.hstack((C,A))
NOVA_MATRIZ = np.vstack((TOPO, BAIXO))
NOVA_MATRIZ

array([[55, 56, 57, 58, 59, 50, 51, 52, 53, 54],
       [65, 66, 67, 68, 69, 60, 61, 62, 63, 64],
       [75, 76, 77, 78, 79, 70, 71, 72, 73, 74],
       [85, 86, 87, 88, 89, 80, 81, 82, 83, 84],
       [95, 96, 97, 98, 99, 90, 91, 92, 93, 94],
       [ 5,  6,  7,  8,  9,  0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19, 10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29, 20, 21, 22, 23, 24],
       [35, 36, 37, 38, 39, 30, 31, 32, 33, 34],
       [45, 46, 47, 48, 49, 40, 41, 42, 43, 44]])

**Exercício 5-4**

In [41]:
MATRIZ_A = np.array([[2, 4],
                     [6, 8]])

MATRIZ_B = np.array([[8, 6],
                     [4, 2]])

MATRIZ_C = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        MATRIZ_C[i, j] = MATRIZ_A[i, j] + MATRIZ_B[i, j]

print(MATRIZ_C)


[[10. 10.]
 [10. 10.]]


**Exercise 5-5**

In [43]:
MATRIZ_A = np.random.randn(3, 4)
MATRIZ_B = np.random.randn(3, 4)

ESCALAR = np.random.randn()

RESULTADO_1 = ESCALAR * (MATRIZ_A + MATRIZ_B)
RESULTADO_2 = ESCALAR * MATRIZ_A + ESCALAR * MATRIZ_B
RESULTADO_3 = MATRIZ_A * ESCALAR + MATRIZ_B * ESCALAR

print(np.allclose(RESULTADO_1, RESULTADO_2))
print(np.allclose(RESULTADO_1, RESULTADO_3))

True
True


**Exercise 5-6**

In [44]:
MATRIZ_A = np.array([[1, 2, 3],
                     [4, 5, 6]])

MATRIZ_B = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

MATRIZ_C = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        for k in range(3):
            MATRIZ_C[i, j] += MATRIZ_A[i, k] * MATRIZ_B[k, j]

print("Com os for:")
print(MATRIZ_C)

print("\nCom @:")
print(MATRIZ_A @ MATRIZ_B)

Com os for:
[[ 58.  64.]
 [139. 154.]]

Com @:
[[ 58  64]
 [139 154]]


**Exercise 5-7**

In [48]:
L = np.random.randn(2, 6)
I = np.random.randn(6, 3)
V = np.random.randn(3, 5)
E = np.random.randn(5, 2)

RESULTADO_1 = (L @ I @ V @ E).T

RESULTADO_2 = L.T @ I.T @ V.T @ E.T

RESULTADO_3 = E.T @ V.T @ I.T @ L.T

print("Resultado original transposto:")
print(RESULTADO_1)

print("\nResultado sem inverter:")
print(RESULTADO_2)

print("\nResultado invertendo:")
print(RESULTADO_3)



ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

**Exercise 5-8**

In [49]:
def eh_simetrica(M):
    return np.allclose(M, M.T)

MATRIZ_A = np.array([[1, 2, 3],
                     [2, 5, 6],
                     [3, 6, 9]])

MATRIZ_B = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(eh_simetrica(MATRIZ_A))
print(eh_simetrica(MATRIZ_B))

True
False


**Exercise 5-9**

In [50]:
MATRIZ_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

MATRIZ_SIMETRICA = (MATRIZ_A + MATRIZ_A.T) / 2

print(MATRIZ_SIMETRICA)

[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]


**Exercise 5-10**

In [51]:
V1 = np.array([1, 2, 3])
V2 = np.array([4, 5, 6])

A = np.column_stack((V1, V2))

S = np.array([2, 3])

RESULTADO = A @ S

print(RESULTADO)

[14 19 24]


**Exercise 5-11**

In [52]:
MATRIZ_UNS = np.ones((4, 4))

MATRIZ_DIAGONAL = np.diag([1, 4, 9, 16])

MATRIZ_RAIZ = np.diag(np.sqrt([1, 4, 9, 16]))

print("Pré-multiplicação:")
print(MATRIZ_DIAGONAL @ MATRIZ_UNS)

print("\nPós-multiplicação:")
print(MATRIZ_UNS @ MATRIZ_DIAGONAL)

print("\nPré e pós com a raiz:")
print(MATRIZ_RAIZ @ MATRIZ_UNS @ MATRIZ_RAIZ)

Pré-multiplicação:
[[ 1.  1.  1.  1.]
 [ 4.  4.  4.  4.]
 [ 9.  9.  9.  9.]
 [16. 16. 16. 16.]]

Pós-multiplicação:
[[ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]]

Pré e pós com a raiz:
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


**Exercise 5-12**

In [53]:
A = np.diag([2, 3, 4])
B = np.diag([5, 6, 7])

RESULTADO_MATRIZ = A @ B
RESULTADO_HADAMARD = A * B

print("Multiplicação matricial:")
print(RESULTADO_MATRIZ)

print("\nMultiplicação Hadamard:")
print(RESULTADO_HADAMARD)

print("\nSão iguais?")
print(np.allclose(RESULTADO_MATRIZ, RESULTADO_HADAMARD))

Multiplicação matricial:
[[10  0  0]
 [ 0 18  0]
 [ 0  0 28]]

Multiplicação Hadamard:
[[10  0  0]
 [ 0 18  0]
 [ 0  0 28]]

São iguais?
True
